[project]
name = "mcp-image-generator"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "mcp[cli]>=1.13",
    "google-generativeai>=0.5.4",
    "python-dotenv>=1.0.1",
]

[project.scripts]
mcp-nano-banana = "image_generator_mcp:main"

[tool.setuptools.packages.find]
where = ["src"]